const meatPrice = 123.965;
const fishPrice = 90.2345;
const vegetablesPrice = 15.678;
const MaxPrice = Math.max(meatPrice, fishPrice, vegetablesPrice);
const MinPrice = Math.min(meatPrice, fishPrice, vegetablesPrice);
const AllPrice = (meatPrice + fishPrice + vegetablesPrice).toFixed(1);
const minRoundPrice = Math.floor(meatPrice) + Math.floor(fishPrice) + Math.floor(vegetablesPrice);
const maxRoundPrice = Math.ceil((AllPrice / 100)) * 100;
const sumProduct = minRoundPrice % 2 == 0 ? true : false;
const remainder = (500 - AllPrice).toFixed(1);
const averagePrice = (AllPrice / 3).toFixed(2);
const discount = Math.random().toFixed(2);
const toPay = (AllPrice - discount).toFixed(1);
const profit = (AllPrice / 2);
const netProfit = (profit - discount).toFixed(2);

console.log(`Максимальне число: ${MaxPrice}`);
console.log(`Мінімальне число: ${MinPrice}`);
console.log(`Загальна вартість всіх товарів складає: ${AllPrice}`);
console.log(`Сума всіх товарів з заокругленням в меншу сторону: ${minRoundPrice}`);
console.log(`Сума округлення до сотень: ${maxRoundPrice}`);
console.log(`Чи є сума усіх товарів парною: ${sumProduct}`);
console.log(`Сума решти: ${remainder}`);
console.log(`Середнє значення цін: ${averagePrice}`);
console.log(`Ваша знижка складає: ${discount}%`);
console.log(`Сума до сплати зі знижкою: ${toPay}`);
console.log(`Чистий прибуток складає: ${netProfit}`);

document.getElementById("MaxPrice").innerHTML = `Максимальне число: ${MaxPrice}`;
document.getElementById("MinPrice").innerHTML = `Мінімальне число: ${MinPrice}`;
document.getElementById("AllPrice").innerHTML = `Загальна вартість всіх товарів складає: ${AllPrice}`;
document.getElementById("minRoundPrice").innerHTML = `Сума всіх товарів з заокругленням в меншу сторону: ${minRoundPrice}`;
document.getElementById("maxRoundPrice").innerHTML = `Сума округлення до сотень: ${maxRoundPrice}`;
document.getElementById("sumProduct").innerHTML = `Чи є сума усіх товарів парною: ${sumProduct}`;
document.getElementById("remainder").innerHTML = `Сума решти: ${remainder}`;
document.getElementById("averagePrice").innerHTML = `Середнє значення цін: ${averagePrice}`;
document.getElementById("discount").innerHTML = `Ваша знижка складає: ${discount}%`;
document.getElementById("toPay").innerHTML = `Сума до сплати зі знижкою: ${toPay}`;
document.getElementById("netProfit").innerHTML = `Чистий прибуток складає: ${netProfit}`;
